spring:
  # Database (DataSource)
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-api
    username: postgres
    password: 123456

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

# JWT
api:
  security:
    token:
      secret: my-secret-key